/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as WhereToBuyRouteImport } from './routes/where-to-buy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CataloguesRouteImport } from './routes/catalogues'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeoTopicRouteImport } from './routes/seo.$topic'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereToBuyRoute = WhereToBuyRouteImport.update({
  id: '/where-to-buy',
  path: '/where-to-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CataloguesRoute = CataloguesRouteImport.update({
  id: '/catalogues',
  path: '/catalogues',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoTopicRoute = SeoTopicRouteImport.update({
  id: '/seo/$topic',
  path: '/seo/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/recipes': typeof RecipesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/wholesale': typeof WholesaleRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seo/$topic': typeof SeoTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/recipes': typeof RecipesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/wholesale': typeof WholesaleRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seo/$topic': typeof SeoTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/recipes': typeof RecipesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/wholesale': typeof WholesaleRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seo/$topic': typeof SeoTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/catalogues'
    | '/contact'
    | '/products'
    | '/recipes'
    | '/sitemap.xml'
    | '/where-to-buy'
    | '/wholesale'
    | '/products/$slug'
    | '/seo/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/catalogues'
    | '/contact'
    | '/products'
    | '/recipes'
    | '/sitemap.xml'
    | '/where-to-buy'
    | '/wholesale'
    | '/products/$slug'
    | '/seo/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/catalogues'
    | '/contact'
    | '/products'
    | '/recipes'
    | '/sitemap.xml'
    | '/where-to-buy'
    | '/wholesale'
    | '/products/$slug'
    | '/seo/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CataloguesRoute: typeof CataloguesRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RecipesRoute: typeof RecipesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhereToBuyRoute: typeof WhereToBuyRoute
  WholesaleRoute: typeof WholesaleRoute
  SeoTopicRoute: typeof SeoTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-to-buy': {
      id: '/where-to-buy'
      path: '/where-to-buy'
      fullPath: '/where-to-buy'
      preLoaderRoute: typeof WhereToBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogues': {
      id: '/catalogues'
      path: '/catalogues'
      fullPath: '/catalogues'
      preLoaderRoute: typeof CataloguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/$topic': {
      id: '/seo/$topic'
      path: '/seo/$topic'
      fullPath: '/seo/$topic'
      preLoaderRoute: typeof SeoTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CataloguesRoute: CataloguesRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RecipesRoute: RecipesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhereToBuyRoute: WhereToBuyRoute,
  WholesaleRoute: WholesaleRoute,
  SeoTopicRoute: SeoTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
